baseURL: 
defaultTheme: dark
languageCode: en-us
title: Vladimir JerotiÄ‡ ğŸ‘»
theme: PaperMod

menu:
  main: 
    - identifier: Home
      name: Home
      url: /

params:
    defaultTheme: dark

params:
    homeInfoParams:
        Title: Hello there ğŸ‘‹ ğŸ‘‹ ğŸ‘‹
        Content: My name is Vladimir JerotiÄ‡. Scroll down and click on tabs if you want to know more.ğŸ‘‡ï¸ğŸ‘‡ï¸ğŸ‘‡ï¸
        defaultTheme: dark