baseURL: "https://vladimirj.xyz/"
languageCode: en-us
title: Vladimir JerotiÄ‡ ğŸ‘»
theme: PaperMod

menu:
  main: 
    - identifier: Home
      name: Home
      url: /

params:
    homeInfoParams:
        Title: Hello there ğŸ‘‹ ğŸ‘‹ 
        Content: My name is Vladimir JerotiÄ‡. Click on tabs down below if you want to find out more about me. You can also toggle between light and dark mode by clicking on the moon/sun icon next to the little ghost. ğŸ‘‡ï¸
        defaultTheme: dark
        disableThemeToggle: true
    defaultTheme: dark
    #disableThemeToggle: true