baseURL: 
defaultTheme: dark
languageCode: en-us
title: Vladimir JerotiÄ‡ ğŸ‘»
theme: PaperMod

menu:
  main: 
    - identifier: Home
      name: Home
      url: /

params:
    defaultTheme: dark

params:
    homeInfoParams:
        Title: Hello there ğŸ‘‹ ğŸ‘‹ 
        Content: My name is Vladimir JerotiÄ‡. Click on tabs if you want to know more. You can also toggle between light and dark mode by clicking on the moon/sun icon besides the little ghost. ğŸ‘‡ï¸
        defaultTheme: dark